<a href="https://colab.research.google.com/github/timztim/data-science-toolkit/blob/main/tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
question1=np.array([[1,2],[3,4]])
print (question1)

[[1 2]
 [3 4]]


In [5]:
question2=np.random.random((3,4))
print(question2)

[[0.33631401 0.51707932 0.10454079 0.9897073 ]
 [0.1433793  0.50001356 0.12797591 0.99566062]
 [0.4800917  0.29619696 0.00821673 0.32357907]]


In [6]:
question3=np.full((2,2),1)
print(question3)

[[1 1]
 [1 1]]


In [7]:
question4=np.full((2,2),0)
print(question4)

[[0 0]
 [0 0]]


In [9]:
question5=np.random.random((6,3))
print(question5)
print()
print(question5.T)

[[0.04611891 0.00518631 0.43896247]
 [0.02090101 0.85362846 0.76100738]
 [0.77609594 0.14060418 0.53592108]
 [0.56157312 0.44689601 0.26656246]
 [0.71992007 0.9146689  0.05281497]
 [0.48034386 0.97368304 0.87486784]]

[[0.04611891 0.02090101 0.77609594 0.56157312 0.71992007 0.48034386]
 [0.00518631 0.85362846 0.14060418 0.44689601 0.9146689  0.97368304]
 [0.43896247 0.76100738 0.53592108 0.26656246 0.05281497 0.87486784]]
